# Generated by Django 5.2.5 on 2025-09-13 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("book-open", "Book Open"),
                            ("message-circle", "Message Circle"),
                            ("graduation-cap", "Graduation Cap"),
                            ("star", "Star"),
                            ("play", "Play"),
                        ],
                        default="users",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("red", "Red"),
                            ("yellow", "Yellow"),
                            ("indigo", "Indigo"),
                        ],
                        default="green",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Feature Card",
                "verbose_name_plural": "Feature Cards",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Taleem Edge", max_length=200)),
                (
                    "subtitle",
                    models.CharField(default="by Rah e Ilahi", max_length=200),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Empowering Your Learning Journey", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="A comprehensive learning management system..."
                    ),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        help_text="Upload hero section video",
                        null=True,
                        upload_to="hero_videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "webm", "avi"]
                            )
                        ],
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Fallback image if video is not available",
                        null=True,
                        upload_to="hero_images/",
                    ),
                ),
                (
                    "video_poster",
                    models.ImageField(
                        blank=True,
                        help_text="Video thumbnail/poster image",
                        null=True,
                        upload_to="video_posters/",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.9, max_digits=2),
                ),
                ("total_students", models.CharField(default="10,000+", max_length=50)),
                ("total_resources", models.CharField(default="500+", max_length=50)),
                (
                    "primary_button_text",
                    models.CharField(default="Get Started Free", max_length=100),
                ),
                (
                    "primary_button_link",
                    models.CharField(default="/auth/signup", max_length=200),
                ),
                (
                    "secondary_button_text",
                    models.CharField(default="Watch Demo", max_length=100),
                ),
                (
                    "secondary_button_link",
                    models.CharField(default="/auth/login", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
    ]
