# Generated by Django 5.2.5 on 2025-09-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("job_title", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("years_of_experience", models.IntegerField()),
                ("bio", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("availability", models.CharField(max_length=255)),
                (
                    "expertise_areas",
                    models.TextField(help_text="Comma-separated values"),
                ),
                (
                    "specializations",
                    models.TextField(help_text="Comma-separated values"),
                ),
                ("languages", models.TextField(help_text="Comma-separated values")),
                ("linkedin_profile", models.URLField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="mentors/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
